### ISSUE TITLE
JTPO is for in the Jurik library functions

### ISSUE THREAD

**Issue by loxx123** [zxweed/simple#3]
Would you mind explaining what JTPO is for in the Jurik library functions? I understand the other code, just trying to figure out what JTPO is. Thanks!

**Comment by loxx123** [comment]
Actually, it looks like a version of Spearman rank correlation. correct me if I'm wrong.

**Comment by zxweed** [comment]
Hi @loxx123, sorry I didn't reply in time. By internal logic, the TPO calculation is very close to the [Mann-Kendall statistical test](https://www.statisticshowto.com/mann-kendall-trend-test/) and yes, they all calculate rank auto-correlation of signal.

I have prepared an example to illustrate both of these indicators:
<img width="957" alt="image" src="https://github.com/zxweed/simple/assets/16319433/acdc0a5a-b2e6-40f9-8868-3229509c4715">
